project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Tutoriel C++"
  navbar:
    search: true
    left:
      - text: Fiches d'aide
        menu:
          - href: cours/vignettes/vector.qmd
      
  favicon: figures/efrei_pantheon.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    margin-header: |
      ![](/figures/AlgoTeam.png)


