project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "EFREI Algo Team - Tutoriel C++"
  navbar:
    search: true
    left:
      - text: Fiches d'aide
        menu:
          - href: cours/fiches/codingame.qmd
          - href: cours/fiches/vector.qmd
          - href: cours/fiches/string.qmd
          - href: cours/fiches/cin-cout.qmd
      - text: Articles détaillés
        menu:
          - href: cours/bases/differences_c.qmd

  favicon: figures/efrei_pantheon.png

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    margin-header: |
      ![](/figures/AlgoTeam.png)


